### ISSUE TITLE
Enhancement request: update the calibration script to accept command line argument to run option 1, 2 or 3

### ISSUE THREAD

**Issue by ngth82** [dualshock-tools/ds4-tools#26]
Enhancement request: update the calibration script to accept command line argument to run option 1, 2 or 3

It would be nice to be able to use these scripts in a larger wrapper script. Would it be possible to add command a single command line argument parser to see if the user wants to calibrate with option 1, 2, or 3?

**Comment by carpikes** [comment]
That's a good idea, I'll do it soon!

**Comment by dualshock-tools** [comment]
The web-ui is meant to replace these scripts. Give it a try: https://dualshock-tools.github.io
